! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Auxiliary Routines File
!
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!
! File                 : gckpp_Util.f90
! Time                 : Wed May  3 09:41:10 2023
! Working directory    : /home/cindylou/ujongebl/mod_dms_12.9.3/KPP/Tropchem
! Equation file        : gckpp.kpp
! Output root filename : gckpp
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Util

  USE gckpp_Parameters
  IMPLICIT NONE

CONTAINS



! User INLINED Utility Functions

! End INLINED Utility Functions

! Utility Functions from KPP_HOME/util/util
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! UTIL - Utility functions
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! ****************************************************************
!
! InitSaveData - Opens the data file for writing
!   Parameters :
!
! ****************************************************************

      SUBROUTINE InitSaveData ()

      USE gckpp_Parameters

      open(10, file='gckpp.dat')

      END SUBROUTINE InitSaveData

! End of InitSaveData function
! ****************************************************************

! ****************************************************************
!
! SaveData - Write LOOKAT species in the data file
!   Parameters :
!
! ****************************************************************

      SUBROUTINE SaveData ()

      USE gckpp_Global
      USE gckpp_Monitor

      INTEGER i

      WRITE(10,999) (TIME-TSTART)/3600.D0,  &
                   (C(LOOKAT(i))/CFACTOR, i=1,NLOOKAT)
999   FORMAT(E24.16,100(1X,E24.16))

      END SUBROUTINE SaveData

! End of SaveData function
! ****************************************************************

! ****************************************************************
!
! CloseSaveData - Close the data file
!   Parameters :
!
! ****************************************************************

      SUBROUTINE CloseSaveData ()

      USE gckpp_Parameters

      CLOSE(10)

      END SUBROUTINE CloseSaveData

! End of CloseSaveData function
! ****************************************************************

! ****************************************************************
!
! GenerateMatlab - Generates MATLAB file to load the data file
!   Parameters :
!                It will have a character string to prefix each
!                species name with.
!
! ****************************************************************

      SUBROUTINE GenerateMatlab ( PREFIX )

      USE gckpp_Parameters
      USE gckpp_Global
      USE gckpp_Monitor


      CHARACTER(LEN=8) PREFIX
      INTEGER i

      open(20, file='gckpp.m')
      write(20,*) 'load gckpp.dat;'
      write(20,990) PREFIX
990   FORMAT(A1,'c = gckpp;')
      write(20,*) 'clear gckpp;'
      write(20,991) PREFIX, PREFIX
991   FORMAT(A1,'t=',A1,'c(:,1);')
      write(20,992) PREFIX
992   FORMAT(A1,'c(:,1)=[];')

      do i=1,NLOOKAT
        write(20,993) PREFIX, SPC_NAMES(LOOKAT(i)), PREFIX, i
993     FORMAT(A1,A6,' = ',A1,'c(:,',I2,');')
      end do

      CLOSE(20)

      END SUBROUTINE GenerateMatlab

! End of GenerateMatlab function
! ****************************************************************


! End Utility Functions from KPP_HOME/util/util
! End of UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Shuffle_user2kpp - function to copy concentrations from USER to KPP
!   Arguments :
!      V_USER    - Concentration of variable species in USER's order
!      V         - Concentrations of variable species (local)
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_user2kpp ( V_USER, V )

! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)
! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)

  V(319) = V_USER(1)
  V(273) = V_USER(2)
  V(249) = V_USER(3)
  V(4) = V_USER(4)
  V(315) = V_USER(5)
  V(180) = V_USER(6)
  V(310) = V_USER(7)
  V(244) = V_USER(8)
  V(318) = V_USER(9)
  V(124) = V_USER(10)
  V(341) = V_USER(11)
  V(189) = V_USER(12)
  V(200) = V_USER(13)
  V(132) = V_USER(14)
  V(217) = V_USER(15)
  V(335) = V_USER(16)
  V(139) = V_USER(17)
  V(336) = V_USER(18)
  V(330) = V_USER(19)
  V(208) = V_USER(20)
  V(187) = V_USER(21)
  V(202) = V_USER(22)
  V(203) = V_USER(23)
  V(120) = V_USER(24)
  V(151) = V_USER(25)
  V(1) = V_USER(26)
  V(2) = V_USER(27)
  V(3) = V_USER(28)
  V(316) = V_USER(29)
  V(311) = V_USER(30)
  V(133) = V_USER(31)
  V(293) = V_USER(32)
  V(164) = V_USER(33)
  V(125) = V_USER(34)
  V(121) = V_USER(35)
  V(152) = V_USER(36)
  V(338) = V_USER(37)
  V(210) = V_USER(38)
  V(153) = V_USER(39)
  V(281) = V_USER(40)
  V(284) = V_USER(41)
  V(340) = V_USER(42)
  V(172) = V_USER(43)
  V(322) = V_USER(44)
  V(5) = V_USER(45)
  V(261) = V_USER(46)
  V(196) = V_USER(47)
  V(264) = V_USER(48)
  V(165) = V_USER(49)
  V(266) = V_USER(50)
  V(174) = V_USER(51)
  V(292) = V_USER(52)
  V(269) = V_USER(53)
  V(225) = V_USER(54)
  V(307) = V_USER(55)
  V(337) = V_USER(56)
  V(248) = V_USER(57)
  V(326) = V_USER(58)
  V(254) = V_USER(59)
  V(140) = V_USER(60)
  V(145) = V_USER(61)
  V(166) = V_USER(62)
  V(211) = V_USER(63)
  V(285) = V_USER(64)
  V(167) = V_USER(65)
  V(327) = V_USER(66)
  V(271) = V_USER(67)
  V(267) = V_USER(68)
  V(272) = V_USER(69)
  V(197) = V_USER(70)
  V(245) = V_USER(71)
  V(184) = V_USER(72)
  V(246) = V_USER(73)
  V(185) = V_USER(74)
  V(191) = V_USER(75)
  V(192) = V_USER(76)
  V(234) = V_USER(77)
  V(324) = V_USER(78)
  V(204) = V_USER(79)
  V(126) = V_USER(80)
  V(134) = V_USER(81)
  V(117) = V_USER(82)
  V(154) = V_USER(83)
  V(236) = V_USER(84)
  V(251) = V_USER(85)
  V(169) = V_USER(86)
  V(298) = V_USER(87)
  V(213) = V_USER(88)
  V(262) = V_USER(89)
  V(175) = V_USER(90)
  V(193) = V_USER(91)
  V(205) = V_USER(92)
  V(290) = V_USER(93)
  V(230) = V_USER(94)
  V(231) = V_USER(95)
  V(227) = V_USER(96)
  V(301) = V_USER(97)
  V(209) = V_USER(98)
  V(198) = V_USER(99)
  V(286) = V_USER(100)
  V(199) = V_USER(101)
  V(287) = V_USER(102)
  V(186) = V_USER(103)
  V(280) = V_USER(104)
  V(206) = V_USER(105)
  V(207) = V_USER(106)
  V(270) = V_USER(107)
  V(302) = V_USER(108)
  V(303) = V_USER(109)
  V(275) = V_USER(110)
  V(250) = V_USER(111)
  V(241) = V_USER(112)
  V(242) = V_USER(113)
  V(247) = V_USER(114)
  V(194) = V_USER(115)
  V(6) = V_USER(116)
  V(141) = V_USER(117)
  V(308) = V_USER(118)
  V(309) = V_USER(119)
  V(240) = V_USER(120)
  V(218) = V_USER(121)
  V(325) = V_USER(122)
  V(168) = V_USER(123)
  V(257) = V_USER(124)
  V(283) = V_USER(125)
  V(163) = V_USER(126)
  V(7) = V_USER(127)
  V(8) = V_USER(128)
  V(277) = V_USER(129)
  V(229) = V_USER(130)
  V(222) = V_USER(131)
  V(274) = V_USER(132)
  V(300) = V_USER(133)
  V(312) = V_USER(134)
  V(9) = V_USER(135)
  V(10) = V_USER(136)
  V(235) = V_USER(137)
  V(294) = V_USER(138)
  V(11) = V_USER(139)
  V(12) = V_USER(140)
  V(13) = V_USER(141)
  V(14) = V_USER(142)
  V(16) = V_USER(143)
  V(15) = V_USER(144)
  V(17) = V_USER(145)
  V(18) = V_USER(146)
  V(306) = V_USER(147)
  V(265) = V_USER(148)
  V(201) = V_USER(149)
  V(305) = V_USER(150)
  V(147) = V_USER(151)
  V(321) = V_USER(152)
  V(195) = V_USER(153)
  V(226) = V_USER(154)
  V(256) = V_USER(155)
  V(237) = V_USER(156)
  V(288) = V_USER(157)
  V(260) = V_USER(158)
  V(282) = V_USER(159)
  V(162) = V_USER(160)
  V(291) = V_USER(161)
  V(323) = V_USER(162)
  V(276) = V_USER(163)
  V(122) = V_USER(164)
  V(239) = V_USER(165)
  V(255) = V_USER(166)
  V(190) = V_USER(167)
  V(223) = V_USER(168)
  V(149) = V_USER(169)
  V(135) = V_USER(170)
  V(216) = V_USER(171)
  V(219) = V_USER(172)
  V(304) = V_USER(173)
  V(182) = V_USER(174)
  V(233) = V_USER(175)
  V(243) = V_USER(176)
  V(289) = V_USER(177)
  V(297) = V_USER(178)
  V(259) = V_USER(179)
  V(220) = V_USER(180)
  V(212) = V_USER(181)
  V(118) = V_USER(182)
  V(119) = V_USER(183)
  V(332) = V_USER(184)
  V(339) = V_USER(185)
  V(334) = V_USER(186)
  V(155) = V_USER(187)
  V(331) = V_USER(189)
  V(173) = V_USER(190)
  V(333) = V_USER(191)
  V(156) = V_USER(192)
  V(279) = V_USER(193)
  V(278) = V_USER(194)
  V(314) = V_USER(195)
  V(142) = V_USER(196)
  V(299) = V_USER(197)
  V(181) = V_USER(198)
  V(268) = V_USER(199)
  V(176) = V_USER(200)
  V(127) = V_USER(201)
  V(263) = V_USER(202)
  V(253) = V_USER(203)
  V(317) = V_USER(204)
  V(177) = V_USER(205)
  V(170) = V_USER(206)
  V(296) = V_USER(207)
  V(258) = V_USER(208)
  V(313) = V_USER(209)
  V(157) = V_USER(210)
  V(158) = V_USER(211)
  V(159) = V_USER(212)
  V(295) = V_USER(213)
  V(320) = V_USER(214)
  V(215) = V_USER(215)
  V(224) = V_USER(216)
  V(232) = V_USER(217)
  V(228) = V_USER(218)
  V(221) = V_USER(219)
  V(160) = V_USER(220)
  V(328) = V_USER(221)
  V(329) = V_USER(222)
  V(178) = V_USER(223)
  V(19) = V_USER(224)
  V(20) = V_USER(225)
  V(21) = V_USER(226)
  V(22) = V_USER(227)
  V(23) = V_USER(228)
  V(24) = V_USER(229)
  V(25) = V_USER(230)
  V(26) = V_USER(231)
  V(27) = V_USER(232)
  V(28) = V_USER(233)
  V(128) = V_USER(234)
  V(136) = V_USER(235)
  V(161) = V_USER(236)
  V(143) = V_USER(237)
  V(171) = V_USER(238)
  V(146) = V_USER(239)
  V(129) = V_USER(240)
  V(238) = V_USER(241)
  V(188) = V_USER(242)
  V(130) = V_USER(243)
  V(214) = V_USER(244)
  V(179) = V_USER(245)
  V(150) = V_USER(246)
  V(29) = V_USER(247)
  V(131) = V_USER(248)
  V(137) = V_USER(249)
  V(183) = V_USER(250)
  V(138) = V_USER(251)
  V(123) = V_USER(252)
  V(144) = V_USER(253)
  V(148) = V_USER(254)
  V(30) = V_USER(255)
  V(31) = V_USER(256)
  V(32) = V_USER(257)
  V(33) = V_USER(258)
  V(34) = V_USER(259)
  V(35) = V_USER(260)
  V(36) = V_USER(261)
  V(37) = V_USER(262)
  V(38) = V_USER(263)
  V(39) = V_USER(264)
  V(40) = V_USER(265)
  V(41) = V_USER(266)
  V(42) = V_USER(267)
  V(43) = V_USER(268)
  V(44) = V_USER(269)
  V(45) = V_USER(270)
  V(46) = V_USER(271)
  V(47) = V_USER(272)
  V(48) = V_USER(273)
  V(49) = V_USER(274)
  V(50) = V_USER(275)
  V(51) = V_USER(276)
  V(52) = V_USER(277)
  V(53) = V_USER(278)
  V(54) = V_USER(279)
  V(55) = V_USER(280)
  V(56) = V_USER(281)
  V(57) = V_USER(282)
  V(58) = V_USER(283)
  V(59) = V_USER(284)
  V(60) = V_USER(285)
  V(252) = V_USER(286)
  V(61) = V_USER(287)
  V(62) = V_USER(288)
  V(63) = V_USER(289)
  V(64) = V_USER(290)
  V(65) = V_USER(291)
  V(66) = V_USER(292)
  V(67) = V_USER(293)
  V(68) = V_USER(294)
  V(69) = V_USER(295)
  V(70) = V_USER(296)
  V(71) = V_USER(297)
  V(72) = V_USER(298)
  V(73) = V_USER(299)
  V(74) = V_USER(300)
  V(75) = V_USER(301)
  V(76) = V_USER(302)
  V(77) = V_USER(303)
  V(78) = V_USER(304)
  V(79) = V_USER(305)
  V(80) = V_USER(306)
  V(81) = V_USER(307)
  V(82) = V_USER(308)
  V(83) = V_USER(309)
  V(84) = V_USER(310)
  V(85) = V_USER(311)
  V(86) = V_USER(312)
  V(87) = V_USER(313)
  V(88) = V_USER(314)
  V(89) = V_USER(315)
  V(90) = V_USER(316)
  V(91) = V_USER(317)
  V(92) = V_USER(318)
  V(93) = V_USER(319)
  V(94) = V_USER(320)
  V(95) = V_USER(321)
  V(96) = V_USER(322)
  V(97) = V_USER(323)
  V(98) = V_USER(324)
  V(99) = V_USER(325)
  V(100) = V_USER(326)
  V(101) = V_USER(327)
  V(102) = V_USER(328)
  V(103) = V_USER(329)
  V(104) = V_USER(330)
  V(105) = V_USER(331)
  V(106) = V_USER(332)
  V(107) = V_USER(333)
  V(108) = V_USER(334)
  V(109) = V_USER(335)
  V(110) = V_USER(336)
  V(111) = V_USER(337)
  V(112) = V_USER(338)
  V(113) = V_USER(339)
  V(114) = V_USER(340)

END SUBROUTINE Shuffle_user2kpp

! End of Shuffle_user2kpp function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Shuffle_kpp2user - function to restore concentrations from KPP to USER
!   Arguments :
!      V         - Concentrations of variable species (local)
!      V_USER    - Concentration of variable species in USER's order
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_kpp2user ( V, V_USER )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)

  V_USER(1) = V(319)
  V_USER(2) = V(273)
  V_USER(3) = V(249)
  V_USER(4) = V(4)
  V_USER(5) = V(315)
  V_USER(6) = V(180)
  V_USER(7) = V(310)
  V_USER(8) = V(244)
  V_USER(9) = V(318)
  V_USER(10) = V(124)
  V_USER(11) = V(341)
  V_USER(12) = V(189)
  V_USER(13) = V(200)
  V_USER(14) = V(132)
  V_USER(15) = V(217)
  V_USER(16) = V(335)
  V_USER(17) = V(139)
  V_USER(18) = V(336)
  V_USER(19) = V(330)
  V_USER(20) = V(208)
  V_USER(21) = V(187)
  V_USER(22) = V(202)
  V_USER(23) = V(203)
  V_USER(24) = V(120)
  V_USER(25) = V(151)
  V_USER(26) = V(1)
  V_USER(27) = V(2)
  V_USER(28) = V(3)
  V_USER(29) = V(316)
  V_USER(30) = V(311)
  V_USER(31) = V(133)
  V_USER(32) = V(293)
  V_USER(33) = V(164)
  V_USER(34) = V(125)
  V_USER(35) = V(121)
  V_USER(36) = V(152)
  V_USER(37) = V(338)
  V_USER(38) = V(210)
  V_USER(39) = V(153)
  V_USER(40) = V(281)
  V_USER(41) = V(284)
  V_USER(42) = V(340)
  V_USER(43) = V(172)
  V_USER(44) = V(322)
  V_USER(45) = V(5)
  V_USER(46) = V(261)
  V_USER(47) = V(196)
  V_USER(48) = V(264)
  V_USER(49) = V(165)
  V_USER(50) = V(266)
  V_USER(51) = V(174)
  V_USER(52) = V(292)
  V_USER(53) = V(269)
  V_USER(54) = V(225)
  V_USER(55) = V(307)
  V_USER(56) = V(337)
  V_USER(57) = V(248)
  V_USER(58) = V(326)
  V_USER(59) = V(254)
  V_USER(60) = V(140)
  V_USER(61) = V(145)
  V_USER(62) = V(166)
  V_USER(63) = V(211)
  V_USER(64) = V(285)
  V_USER(65) = V(167)
  V_USER(66) = V(327)
  V_USER(67) = V(271)
  V_USER(68) = V(267)
  V_USER(69) = V(272)
  V_USER(70) = V(197)
  V_USER(71) = V(245)
  V_USER(72) = V(184)
  V_USER(73) = V(246)
  V_USER(74) = V(185)
  V_USER(75) = V(191)
  V_USER(76) = V(192)
  V_USER(77) = V(234)
  V_USER(78) = V(324)
  V_USER(79) = V(204)
  V_USER(80) = V(126)
  V_USER(81) = V(134)
  V_USER(82) = V(117)
  V_USER(83) = V(154)
  V_USER(84) = V(236)
  V_USER(85) = V(251)
  V_USER(86) = V(169)
  V_USER(87) = V(298)
  V_USER(88) = V(213)
  V_USER(89) = V(262)
  V_USER(90) = V(175)
  V_USER(91) = V(193)
  V_USER(92) = V(205)
  V_USER(93) = V(290)
  V_USER(94) = V(230)
  V_USER(95) = V(231)
  V_USER(96) = V(227)
  V_USER(97) = V(301)
  V_USER(98) = V(209)
  V_USER(99) = V(198)
  V_USER(100) = V(286)
  V_USER(101) = V(199)
  V_USER(102) = V(287)
  V_USER(103) = V(186)
  V_USER(104) = V(280)
  V_USER(105) = V(206)
  V_USER(106) = V(207)
  V_USER(107) = V(270)
  V_USER(108) = V(302)
  V_USER(109) = V(303)
  V_USER(110) = V(275)
  V_USER(111) = V(250)
  V_USER(112) = V(241)
  V_USER(113) = V(242)
  V_USER(114) = V(247)
  V_USER(115) = V(194)
  V_USER(116) = V(6)
  V_USER(117) = V(141)
  V_USER(118) = V(308)
  V_USER(119) = V(309)
  V_USER(120) = V(240)
  V_USER(121) = V(218)
  V_USER(122) = V(325)
  V_USER(123) = V(168)
  V_USER(124) = V(257)
  V_USER(125) = V(283)
  V_USER(126) = V(163)
  V_USER(127) = V(7)
  V_USER(128) = V(8)
  V_USER(129) = V(277)
  V_USER(130) = V(229)
  V_USER(131) = V(222)
  V_USER(132) = V(274)
  V_USER(133) = V(300)
  V_USER(134) = V(312)
  V_USER(135) = V(9)
  V_USER(136) = V(10)
  V_USER(137) = V(235)
  V_USER(138) = V(294)
  V_USER(139) = V(11)
  V_USER(140) = V(12)
  V_USER(141) = V(13)
  V_USER(142) = V(14)
  V_USER(143) = V(16)
  V_USER(144) = V(15)
  V_USER(145) = V(17)
  V_USER(146) = V(18)
  V_USER(147) = V(306)
  V_USER(148) = V(265)
  V_USER(149) = V(201)
  V_USER(150) = V(305)
  V_USER(151) = V(147)
  V_USER(152) = V(321)
  V_USER(153) = V(195)
  V_USER(154) = V(226)
  V_USER(155) = V(256)
  V_USER(156) = V(237)
  V_USER(157) = V(288)
  V_USER(158) = V(260)
  V_USER(159) = V(282)
  V_USER(160) = V(162)
  V_USER(161) = V(291)
  V_USER(162) = V(323)
  V_USER(163) = V(276)
  V_USER(164) = V(122)
  V_USER(165) = V(239)
  V_USER(166) = V(255)
  V_USER(167) = V(190)
  V_USER(168) = V(223)
  V_USER(169) = V(149)
  V_USER(170) = V(135)
  V_USER(171) = V(216)
  V_USER(172) = V(219)
  V_USER(173) = V(304)
  V_USER(174) = V(182)
  V_USER(175) = V(233)
  V_USER(176) = V(243)
  V_USER(177) = V(289)
  V_USER(178) = V(297)
  V_USER(179) = V(259)
  V_USER(180) = V(220)
  V_USER(181) = V(212)
  V_USER(182) = V(118)
  V_USER(183) = V(119)
  V_USER(184) = V(332)
  V_USER(185) = V(339)
  V_USER(186) = V(334)
  V_USER(187) = V(155)
  V_USER(189) = V(331)
  V_USER(190) = V(173)
  V_USER(191) = V(333)
  V_USER(192) = V(156)
  V_USER(193) = V(279)
  V_USER(194) = V(278)
  V_USER(195) = V(314)
  V_USER(196) = V(142)
  V_USER(197) = V(299)
  V_USER(198) = V(181)
  V_USER(199) = V(268)
  V_USER(200) = V(176)
  V_USER(201) = V(127)
  V_USER(202) = V(263)
  V_USER(203) = V(253)
  V_USER(204) = V(317)
  V_USER(205) = V(177)
  V_USER(206) = V(170)
  V_USER(207) = V(296)
  V_USER(208) = V(258)
  V_USER(209) = V(313)
  V_USER(210) = V(157)
  V_USER(211) = V(158)
  V_USER(212) = V(159)
  V_USER(213) = V(295)
  V_USER(214) = V(320)
  V_USER(215) = V(215)
  V_USER(216) = V(224)
  V_USER(217) = V(232)
  V_USER(218) = V(228)
  V_USER(219) = V(221)
  V_USER(220) = V(160)
  V_USER(221) = V(328)
  V_USER(222) = V(329)
  V_USER(223) = V(178)
  V_USER(224) = V(19)
  V_USER(225) = V(20)
  V_USER(226) = V(21)
  V_USER(227) = V(22)
  V_USER(228) = V(23)
  V_USER(229) = V(24)
  V_USER(230) = V(25)
  V_USER(231) = V(26)
  V_USER(232) = V(27)
  V_USER(233) = V(28)
  V_USER(234) = V(128)
  V_USER(235) = V(136)
  V_USER(236) = V(161)
  V_USER(237) = V(143)
  V_USER(238) = V(171)
  V_USER(239) = V(146)
  V_USER(240) = V(129)
  V_USER(241) = V(238)
  V_USER(242) = V(188)
  V_USER(243) = V(130)
  V_USER(244) = V(214)
  V_USER(245) = V(179)
  V_USER(246) = V(150)
  V_USER(247) = V(29)
  V_USER(248) = V(131)
  V_USER(249) = V(137)
  V_USER(250) = V(183)
  V_USER(251) = V(138)
  V_USER(252) = V(123)
  V_USER(253) = V(144)
  V_USER(254) = V(148)
  V_USER(255) = V(30)
  V_USER(256) = V(31)
  V_USER(257) = V(32)
  V_USER(258) = V(33)
  V_USER(259) = V(34)
  V_USER(260) = V(35)
  V_USER(261) = V(36)
  V_USER(262) = V(37)
  V_USER(263) = V(38)
  V_USER(264) = V(39)
  V_USER(265) = V(40)
  V_USER(266) = V(41)
  V_USER(267) = V(42)
  V_USER(268) = V(43)
  V_USER(269) = V(44)
  V_USER(270) = V(45)
  V_USER(271) = V(46)
  V_USER(272) = V(47)
  V_USER(273) = V(48)
  V_USER(274) = V(49)
  V_USER(275) = V(50)
  V_USER(276) = V(51)
  V_USER(277) = V(52)
  V_USER(278) = V(53)
  V_USER(279) = V(54)
  V_USER(280) = V(55)
  V_USER(281) = V(56)
  V_USER(282) = V(57)
  V_USER(283) = V(58)
  V_USER(284) = V(59)
  V_USER(285) = V(60)
  V_USER(286) = V(252)
  V_USER(287) = V(61)
  V_USER(288) = V(62)
  V_USER(289) = V(63)
  V_USER(290) = V(64)
  V_USER(291) = V(65)
  V_USER(292) = V(66)
  V_USER(293) = V(67)
  V_USER(294) = V(68)
  V_USER(295) = V(69)
  V_USER(296) = V(70)
  V_USER(297) = V(71)
  V_USER(298) = V(72)
  V_USER(299) = V(73)
  V_USER(300) = V(74)
  V_USER(301) = V(75)
  V_USER(302) = V(76)
  V_USER(303) = V(77)
  V_USER(304) = V(78)
  V_USER(305) = V(79)
  V_USER(306) = V(80)
  V_USER(307) = V(81)
  V_USER(308) = V(82)
  V_USER(309) = V(83)
  V_USER(310) = V(84)
  V_USER(311) = V(85)
  V_USER(312) = V(86)
  V_USER(313) = V(87)
  V_USER(314) = V(88)
  V_USER(315) = V(89)
  V_USER(316) = V(90)
  V_USER(317) = V(91)
  V_USER(318) = V(92)
  V_USER(319) = V(93)
  V_USER(320) = V(94)
  V_USER(321) = V(95)
  V_USER(322) = V(96)
  V_USER(323) = V(97)
  V_USER(324) = V(98)
  V_USER(325) = V(99)
  V_USER(326) = V(100)
  V_USER(327) = V(101)
  V_USER(328) = V(102)
  V_USER(329) = V(103)
  V_USER(330) = V(104)
  V_USER(331) = V(105)
  V_USER(332) = V(106)
  V_USER(333) = V(107)
  V_USER(334) = V(108)
  V_USER(335) = V(109)
  V_USER(336) = V(110)
  V_USER(337) = V(111)
  V_USER(338) = V(112)
  V_USER(339) = V(113)
  V_USER(340) = V(114)

END SUBROUTINE Shuffle_kpp2user

! End of Shuffle_kpp2user function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! GetMass - compute total mass of selected atoms
!   Arguments :
!      CL        - Concentration of all species (local)
!      Mass      - value of mass balance
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE GetMass ( CL, Mass )

! CL - Concentration of all species (local)
  REAL(kind=dp) :: CL(NSPEC)
! Mass - value of mass balance
  REAL(kind=dp) :: Mass(1)


END SUBROUTINE GetMass

! End of GetMass function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! Get_OHreactivity - returns the OH reactivity
! The OH reactivity is defined as the inverse of its lifetime.
! This routine was auto-generated using script OHreact_parser.py.
! Generated on 2023-05-03
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Get_OHreactivity ( CC, RR, OHreact )

! CC - Concentrations of species (local)
  REAL(kind=dp) :: CC(NSPEC)
! RR - reaction rates (local)
  REAL(kind=dp) :: RR(NREACT)
! OHreact - OH reactivity [s-1]
  REAL(kind=dp) :: OHreact

  OHreact = RR(2)*CC(331) + 2*RR(6) + 2*RR(7) + RR(8)*CC(327) + RR(9)*CC(225) &
          + RR(12)*CC(343) + RR(13)*CC(322) + RR(14)*CC(342) + RR(20)*CC(190) + RR(21)*CC(190) &
          + RR(22)*CC(244) + RR(23)*CC(244) + RR(24)*CC(316) + RR(25)*CC(339) + RR(26)*CC(285) &
          + RR(27)*CC(332) + RR(28)*CC(211) + RR(31)*CC(167) + RR(34)*CC(334) + RR(37)*CC(254) &
          + RR(38)*CC(276) + RR(41)*CC(315) + RR(46)*CC(208) + RR(50)*CC(187) + RR(51)*CC(187) &
          + RR(55)*CC(180) + RR(65)*CC(258) + RR(66)*CC(249) + RR(67)*CC(295) + RR(72)*CC(273) &
          + RR(81)*CC(282) + RR(91)*CC(196) + RR(92)*CC(221) + RR(102)*CC(317) + RR(104)*CC(292) &
          + RR(105)*CC(292) + RR(107)*CC(269) + RR(108)*CC(291) + RR(111)*CC(307) + RR(112)*CC(307) &
          + RR(119)*CC(177) + RR(120)*CC(174) + RR(121)*CC(158) + RR(122)*CC(159) + RR(123)*CC(157) &
          + RR(124)*CC(160) + RR(125)*CC(176) + RR(126)*CC(16) + RR(127)*CC(147) + RR(152)*CC(261) &
          + RR(157)*CC(171) + RR(158)*CC(146) + RR(160)*CC(261) + RR(181)*CC(129) + RR(188)*CC(178) &
          + RR(189)*CC(252) + RR(193)*CC(337) + RR(198)*CC(189) + RR(199)*CC(335) + RR(208)*CC(121) &
          + RR(209)*CC(120) + RR(210)*CC(133) + RR(211)*CC(210) + RR(213)*CC(340) + RR(214)*CC(340) &
          + RR(215)*CC(173) + RR(216)*CC(153) + RR(217)*CC(326) + RR(218)*CC(267) + RR(219)*CC(281) &
          + RR(220)*CC(284) + RR(221)*CC(164) + RR(222)*CC(151) + RR(223)*CC(152) + RR(286)*CC(204) &
          + RR(287)*CC(140) + RR(288)*CC(272) + RR(295)*CC(125) + RR(296)*CC(264) + RR(297)*CC(253) &
          + RR(313)*CC(124) + RR(314)*CC(128) + RR(315)*CC(161) + RR(323)*CC(216) + RR(324)*CC(219) &
          + RR(334)*CC(235) + RR(342)*CC(181) + RR(356)*CC(239) + RR(357)*CC(255) + RR(363)*CC(197) &
          + RR(364)*CC(162) + RR(365)*CC(165) + RR(366)*CC(163) + RR(367)*CC(155) + RR(369)*CC(277) &
          + RR(370)*CC(277) + RR(371)*CC(277) + RR(372)*CC(277) + RR(399)*CC(245) + RR(400)*CC(246) &
          + RR(401)*CC(191) + RR(402)*CC(192) + RR(403)*CC(248) + RR(404)*CC(236) + RR(405)*CC(175) &
          + RR(406)*CC(215) + RR(407)*CC(215) + RR(408)*CC(224) + RR(409)*CC(224) + RR(410)*CC(215) &
          + RR(411)*CC(224) + RR(412)*CC(232) + RR(413)*CC(228) + RR(426)*CC(186) + RR(427)*CC(198) &
          + RR(428)*CC(198) + RR(429)*CC(199) + RR(430)*CC(199) + RR(449)*CC(206) + RR(450)*CC(206) &
          + RR(451)*CC(207) + RR(452)*CC(207) + RR(453)*CC(280) + RR(454)*CC(280) + RR(455)*CC(270) &
          + RR(456)*CC(270) + RR(457)*CC(280) + RR(458)*CC(270) + RR(496)*CC(240) + RR(497)*CC(218) &
          + RR(498)*CC(240) + RR(499)*CC(218) + RR(500)*CC(218) + RR(501)*CC(240) + RR(502)*CC(218) &
          + RR(503)*CC(218) + RR(512)*CC(298) + RR(513)*CC(298) + RR(516)*CC(301) + RR(519)*CC(304) &
          + RR(521)*CC(306) + RR(522)*CC(306) + RR(525)*CC(297) + RR(526)*CC(289) + RR(527)*CC(288) &
          + RR(528)*CC(256) + RR(529)*CC(237) + RR(536)*CC(226) + RR(537)*CC(220) + RR(538)*CC(182) &
          + RR(539)*CC(243) + RR(540)*CC(233) + RR(541)*CC(195) + RR(547)*CC(201) + RR(559)*CC(223) &
          + RR(560)*CC(166) + RR(561)*CC(262) + RR(562)*CC(193) + RR(563)*CC(205) + RR(564)*CC(227) &
          + RR(565)*CC(274) + RR(566)*CC(300) + RR(568)*CC(170) + RR(569)*CC(145) + RR(571)*CC(234) &
          + RR(572)*CC(234) + RR(615)*CC(328) + RR(616)*CC(329) + RR(675)*CC(171) + RR(676)*CC(146) &
          + RR(678)*CC(135)

END SUBROUTINE Get_OHreactivity
! End of Get_OHreactivity subroutine
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

END MODULE gckpp_Util
